/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    NutAvatar: typeof import("@nutui/nutui")["Avatar"];
    NutButton: typeof import("@nutui/nutui")["Button"];
    NutCard: typeof import("@nutui/nutui")["Card"];
    NutCell: typeof import("@nutui/nutui")["Cell"];
    NutCellGroup: typeof import("@nutui/nutui")["CellGroup"];
    NutForm: typeof import("@nutui/nutui")["Form"];
    NutFormItem: typeof import("@nutui/nutui")["FormItem"];
    NutGrid: typeof import("@nutui/nutui")["Grid"];
    NutGridItem: typeof import("@nutui/nutui")["GridItem"];
    NutNavbar: typeof import("@nutui/nutui")["Navbar"];
    NutSwiper: typeof import("@nutui/nutui")["Swiper"];
    NutSwiperItem: typeof import("@nutui/nutui")["SwiperItem"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
